#!/usr/bin/with-contenv sh

#set -x

source /etc/colors.sh

PREFFIX="[services.d] [rclone-mount]-$(s6-basename ${0}):"

echo -e "${PREFFIX} ${Green}starting rclone mount $(date +%Y.%m.%d-%T)${Color_Off}"

if [ "$Proxy" = true ]; then
    FULLPROXY="${ProxyTarget}:${ProxyPort}"
    export HTTP_PROXY=$FULLPROXY
    export HTTPS_PROXY=$FULLPROXY
    echo -e "SET HTTPProxy ${FULLPROXY}"
else
	echo -e "UNUSE HTTPProxy"
fi

## ECHO DEBUG
if [ "$DEBUG" = true ]; then
    echo -e "${PREFFIX} [DEBUG] command: /usr/sbin/rclone --config $ConfigPath mount $RemotePath $MountPoint $MountCommands"
fi

/usr/sbin/rclone --config $ConfigPath mount $RemotePath $MountPoint $MountCommands
